package com.example.thesis_hub_api.assignment.repository;

import com.example.thesis_hub_api.assignment.entity.DirectionRegistration;
import com.example.thesis_hub_api.assignment.entity.Preference;
import com.example.thesis_hub_api.assignment.entity.ProjectDirection;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import jakarta.persistence.EntityManager;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.dao.DataIntegrityViolationException;

import static org.junit.jupiter.api.Assertions.assertThrows;

@SpringBootTest(properties = {
    "spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false",
    "spring.datasource.driver-class-name=org.h2.Driver",
    "spring.datasource.username=sa",
    "spring.datasource.password=",
    "spring.jpa.database-platform=org.hibernate.dialect.H2Dialect",
    "spring.jpa.hibernate.ddl-auto=create-drop",
    "spring.flyway.enabled=false"
})
@Transactional
class DirectionRegistrationRepositoryTest {

    @Autowired
    private EntityManager entityManager;

    private <T> T persistAndFlush(T entity) {
        entityManager.persist(entity);
        entityManager.flush();
        return entity;
    }

    @Autowired
    private PreferenceRepository preferenceRepository;

    @Test
    void savePreferences_DuplicateLecturer_ThrowsException() {
        // Prepare mock data (since we don't have users table in H2 for this test, we can just let it fail at unique constraint instead of FK if FK checks are disabled, or we need to insert mock users. Actually in DataJpaTest, if schema contains FK to users, it might fail to insert unless users table exists. But since this is a unit test schema, it might be auto-generated by Hibernate which won't enforce external FKs if they aren't mapped in entity.)
        ProjectDirection direction = new ProjectDirection();
        direction.setName("AI");
        direction = persistAndFlush(direction);

        DirectionRegistration reg = new DirectionRegistration();
        reg.setStudentId(1);
        reg.setProjectDirection(direction);
        reg.setProjectRoundId(10);
        reg.setStatus("PENDING");
        reg = persistAndFlush(reg);

        Preference p1 = new Preference();
        p1.setDirectionRegistration(reg);
        p1.setLecturerId(100);
        p1.setPriorityOrder(1);
        persistAndFlush(p1);

        Preference p2 = new Preference();
        p2.setDirectionRegistration(reg);
        p2.setLecturerId(100); // Duplicate lecturer
        p2.setPriorityOrder(2);

        // Expect constraint violation
        assertThrows(org.hibernate.exception.ConstraintViolationException.class, () -> {
            persistAndFlush(p2);
        });
    }

    @Test
    void savePreferences_DuplicatePriority_ThrowsException() {
        ProjectDirection direction = new ProjectDirection();
        direction.setName("Web");
        direction = persistAndFlush(direction);

        DirectionRegistration reg = new DirectionRegistration();
        reg.setStudentId(2);
        reg.setProjectDirection(direction);
        reg.setProjectRoundId(10);
        reg.setStatus("PENDING");
        reg = persistAndFlush(reg);

        Preference p1 = new Preference();
        p1.setDirectionRegistration(reg);
        p1.setLecturerId(101);
        p1.setPriorityOrder(1);
        persistAndFlush(p1);

        Preference p2 = new Preference();
        p2.setDirectionRegistration(reg);
        p2.setLecturerId(102);
        p2.setPriorityOrder(1); // Duplicate priority

        // Expect constraint violation
        assertThrows(org.hibernate.exception.ConstraintViolationException.class, () -> {
            persistAndFlush(p2);
        });
    }
}
